Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "net9/ubuntu-24.04-arm64"
    ubuntu.vm.box_version = "1.1"
    ubuntu.vm.hostname = "ubuntu"
    
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "ubuntu"
    end
  end
end
