Vagrant.configure("2") do |config|
  config.vm.define "kali" do |kali|
    kali.vm.box = "gyptazy/kalilinux-2023.3"
    kali.vm.hostname = "kali"

    kali.vm.provider "vmware_fusion" do |v|
      v.gui = false
      v.vmx["memsize"] = "4096"
      v.vmx["numvcpus"] = "4"
      v.vmx["displayname"] = "kali"
    end
  end
end

