Vagrant.configure("2") do |config|
  config.vm.define "fedora" do |fedora|
    fedora.vm.box = "gyptazy/fedora39-arm64"
    fedora.vm.hostname = "fedora"

    fedora.vm.provider "vmware_fusion" do |v|
      v.gui = false
      v.vmx["memsize"] = "2048"
      v.vmx["numvcpus"] = "2"
      v.vmx["displayname"] = "fedora"
    end
  end
end

